# Generated by Django 5.1.1 on 2024-09-23 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=10)),
                ('PhoneNumber', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_at', models.DateField(auto_now=True)),
                ('Title', models.CharField(max_length=40)),
                ('Content', models.TextField()),
                ('StartTime', models.TimeField(auto_now=True)),
                ('EndTime', models.TimeField(auto_now=True)),
                ('Status', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
