# Generated by Django 5.1.1 on 2024-09-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='User_id',
            new_name='id',
        ),
    ]
