# Generated by Django 5.1.1 on 2024-09-23 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tasks_author_alter_tasks_endtime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='User',
        ),
        migrations.RemoveField(
            model_name='users',
            name='UserName',
        ),
        migrations.AddField(
            model_name='users',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='api.users'),
        ),
    ]
