# Generated by Django 5.1.1 on 2024-09-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_users_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='LastName',
        ),
    ]
