# Generated by Django 5.1.1 on 2024-09-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_users_alter_tasks_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
