# Generated by Django 5.1.1 on 2024-09-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_tasks_author_alter_tasks_id_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
