# Generated by Django 5.1.1 on 2024-09-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
