# Generated by Django 5.1.1 on 2024-09-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Status',
            field=models.BooleanField(),
        ),
    ]
